### ISSUE TITLE
V2: Error logs of 'wrong url'

### ISSUE THREAD

**Issue by LpmRaven** [robinmetral/gatsby-source-s3#134]
Hi @robinmetral, I just upgraded to version 2; great work on getting the sourcing to work with private buckets! 🎉

I'm just testing it out with my websites, one unknown issue I'm getting is all of these error logs; which is unusual as I can confirm the image downloads are successfully and added to the static folder.

<img width="601" alt="Screen Shot 2020-08-14 at 2 08 55 pm" src="https://user-images.githubusercontent.com/6523593/90213277-bab23f00-de38-11ea-83e6-fe650bed717f.png">

I'm looking into this now.

**Comment by robinmetral** [comment]
Thanks for reporting as always, @LpmRaven!

I haven't run into this before, let me know if you figure it out. I can also help debugging if you can provide a reproduction repo 🙂

**Comment by LpmRaven** [comment]
I had leftover code from my v1 implementation using the s3Object Url. In V2, `the Url key doesn't exist on s3Object anymore`.

**Comment by Vacilando** [comment]
I understand key Url is no longer available as such. How can we get the URL of the file (for public buckets) - is there another way in V2? We need it in our project.

**Comment by robinmetral** [comment]
@Vacilando let's talk in #184 🙂
