### ISSUE TITLE
How to handle object expiration with this plugin?

### ISSUE THREAD

**Issue by mindersainii** [robinmetral/gatsby-source-s3#153]
Hi Robin, first of all, thank you very much for this plugin, I had this question and I wasn't sure if this is the right place to it so I apologise in case it's not. I was trying building a photo gallery that has more 1000 photos, so I was using alls3objects>edges>node>url , it is requesting the images but the images are giving 403 error with object expired, I searched on google about the issue and I found that I need to send a request with Presigned URL, I am not that technical so I thought I should ask here if the plugin has some option to do that. Thank you.

**Comment by robinmetral** [comment]
Hi @mindersainii! Thanks for asking 🙂 

The presigned URL is actually used to fetch images in private buckets, i.e. that need auth to access them.

I would guess that this 403 is an issue on the AWS side of things - did you make sure to follow the [AWS setup instructions](https://github.com/robinmetral/gatsby-source-s3#aws-setup) in the README?

**Comment by mindersainii** [comment]
Thank you so much for the quick response :), I actually created the policy using the visual editor first, which was looking bit different than your so I copied ur one used that with updated bucket name and it worked, thank you so much :)

The one I created using Visual editor was this one 
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::bucketname",
                "arn:aws:s3:::bucketname/*"
            ]
        }
    ]
}

**Comment by robinmetral** [comment]
Glad to hear! I'll close this issue then, feel free to open another one if you run into issues 🙂
