### ISSUE TITLE
feat: handle private buckets

### ISSUE THREAD

**Issue by robinmetral** [robinmetral/gatsby-source-s3#24]
The plugin officially doesn't support sourcing from private buckets, although it's been reported to work in #19.

We should investigate if there's anything missing from the plugin to handle private buckets. The README should also be updated with info on how to properly set up a private S3 bucket and IAM role for sourcing with this plugin.

**Comment by robinmetral** [comment]
After investigation, I can confirm that private buckets are **not yet supported** by the plugin.

Neither do the two other Gatsby community plugins ([DSchau/gatsby-source-s3](https://github.com/DSchau/gatsby-source-s3/) and [jessestuart/gatsby-source-s3-image](https://github.com/jessestuart/gatsby-source-s3-image)) - they assume that objects will be public anyways on the Gatsby site, so the buckets can be public as well.

In my opinion, the reasoning behind enabling private buckets is not only for users who may want to keep their buckets private anyways, but mostly because allowing public access is AWS S3 takes an extra step after creating a bucket (AWS discourages it). Enabling sourcing from private buckets would mean that the plugin would work on any bucket with the right IAM policy.

## Why doesn't it work?

After all, the plugin already needs AWS credentials, so why can it not handle private buckets?

The reason is that although the credentials allow programmatic access to the bucket (for example using `ListObjectsV2` to get the contents of a bucket), **the plugin currently relies on the object's public URL** to create the file nodes using `gatsby-source-filesystem`:

https://github.com/robinmetral/gatsby-source-s3/blob/a4f06b44681518aa2802300379c3f7b1700402f2/src/gatsby-node.ts#L126-L135

These URLs return 403s when hit by `gatsby-source-filesystem`, and sourcing the files doesn't succeed.

## How to make it work

There are two solutions to the problem:

1. **Implement pre-signed URLs** to let `gatsby-source-filesystem`'s `createRemoteFileNode` source the file from a temporary URL. This is what was suggested in [this PR to gatsby-source-s3-image](https://github.com/jessestuart/gatsby-source-s3-image/pull/339/files) (but never merged).
2. **Move away from [`createRemoteFileNode`](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createremotefilenode) and use [`createFileNodeFromBuffer`](https://www.gatsbyjs.org/packages/gatsby-source-filesystem/#createfilenodefrombuffer) instead**. Both the other community plugins are using `createRemoteFileNode`, so I never realized that there is an alternative `gatsby-source-filesystem` API to create a file node from a Buffer. This would work, because we can get a Buffer from S3 using [`getObject`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getObject-property) with something like this:
    ```javascript
    s3.getObject(
      { Bucket: "my-bucket", Key: "object.jpg" },
      (err, data) => {
        if (!err) {
          createFileNodeFromBuffer(data.Body); // <= here
        }
      }
    )
    ```

The second option seems like the right choice to me. It also moves towards a cleaner AWS SDK implementation instead of relying on object URLs.

**Comment by robinmetral** [comment]
I spent half a day trying to replace `createRemoteFileNode` by `createFileNodeFromBuffer`, but it didn't work out for me. I'll use pre-signed URLs instead.

I'm documenting what I found here, and I'm open to a PR switching to `createFileNodeFromBuffer` in the future !

## Using `createFileNodeFromBuffer`

### Sourcing Buffers from S3

As far as I could tell, getting Buffers from S3 worked as expected.

The IAM policy needs to be updated to allow `getObject`, like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::gatsby-source-s3-example",
                "arn:aws:s3:::gatsby-source-s3-example-2"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::gatsby-source-s3-example/*",
                "arn:aws:s3:::gatsby-source-s3-example-2/*"
            ]
        }
    ]
}
```

I ended up with a `getObjectBuffer` method like this:

```typescript
const getObjectBuffer = (Bucket: string, Key: string): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    s3.getObject({ Bucket, Key }, (err, data) => {
      if (err) reject(err);
      if (!Buffer.isBuffer(data.Body)) reject(`${Key} is not a Buffer`);
      else resolve();
    });
  });
};
```

### Creating file nodes for S3 buffers

This is where the issue happened for me. I updated a part of the `onCreateNode` implementation ([source](https://github.com/robinmetral/gatsby-source-s3/blob/a4f06b44681518aa2802300379c3f7b1700402f2/src/gatsby-node.ts#L116-L145)) to look like this:

```typescript
// get object buffer
const buffer = await getObjectBuffer(node.Bucket, node.Key);

// create file node
const imageFile = await createFileNodeFromBuffer({
  buffer,
  store,
  cache,
  createNode,
  createNodeId,
  parentNodeId: node.id,
});

// add foreign key relationship
if (imageFile) {
  node.localFile___NODE = imageFile.id; // eslint-disable-line @typescript-eslint/camelcase
}
```

In some of my attempts, I was able to create the file nodes, but I never managed to create the relationship between the parent `S3Object` node and the file node.

The debugging process for source plugins is very hard, because the plugin needs to be properly updated in local examples, and logging errors (either with the Gatsby `reporter` or with Node's `console.log()`) doesn't always work as expected. I don't know exactly why.

## Using pre-signed URLs from S3

After too many unsuccessful attempts, I'm instead opting for using pre-signed URLs.

The implementation was very simple and the feature is on the way: #43

**Comment by LpmRaven** [comment]
Awesome work! 🎉
