### ISSUE TITLE
Can't read markdown file from aws3

### ISSUE THREAD

**Issue by anshif10** [robinmetral/gatsby-source-s3#509]
query IndexQuery {
allS3Image {
edges {
node {
Key
Url
}
}
}
}

npm install @robinmetral/gatsby-source-s3

i am using this plugin,markdown files is s3 bucket,
While using Alls3object query markdown files not read
We are not getting any query, help me please

urgent our project i stuck with this.

thank you

**Comment by Sara14-sudo** [comment]
i also this type problem, plugin @robinmetral/gatsby-source-s3

**Comment by robinmetral** [comment]
Closing as a duplicate of #505, please refer to [this issue comment](https://github.com/robinmetral/gatsby-source-s3/issues/505#issuecomment-915965338).
