### ISSUE TITLE
Error creating file node for S3 object key using Gatsby 4.4

### ISSUE THREAD

**Issue by Vacilando** [robinmetral/gatsby-source-s3#582]
`23:08:41 PM: ERROR Error creating file node for S3 object key "myimage.jpg": TypeError: this is not a Date object.`

This only started happening once we upgraded to Gatsby 4.4.
After downgrading to Gatsby 4.3 the problem disappears.

Do others see this, is there a solution?

**Comment by robinmetral** [comment]
Thanks for reporting! That's strange, I don't see anything that seems related in the changelog for 4.4. Let's see if anyone else is experiencing this, and I'll also try to reproduce when I get the time!

**Comment by robinmetral** [comment]
E2E tests look good in the renovate PR upgrading to 4.4: https://github.com/robinmetral/gatsby-source-s3/pull/587

**Comment by Vacilando** [comment]
Well, I've tried again and see no issues any more. Guess it was a temporary hiccup somewhere at my side, or with the S3 we're using. 
I'll close this. Sorry for the false alarm!

**Comment by robinmetral** [comment]
Thanks for the update!

**Comment by rub1e** [comment]
Hi, I've hit the same thing, it's related to the gatsby build flag `DETECT_NODE_MUTATIONS`.

I'm afraid I've not had a chance to look into why yet, but that's the cause (at least for me).

The images load just fine though, so the nodes do get created.

**Comment by robinmetral** [comment]
Thank you, @rub1e—so turning the flag off got the build to work for you? Let us know if you find anything else, I can also try to look around the Gatsby diff and see if I see anything

**Comment by Vacilando** [comment]
@rub1e & @robinmetral: seems plausible, I think I had the flag on as well at the time of my initial report.
